os: linux
dist: focal
language: python

addons:
  apt:
    packages:
    - libcups2-dev

# addons:
#   apt_packages:
#      - swig
#      - libssl-dev
#      - libssl0.9.8
#      - python-m2crypto
#      - libcups2-dev
#      - unixodbc-dev
#      - python-mysqldb

services:
  - mysql

# before_install:
#     - "export DISPLAY=:99.0"
#     - "sh -e /etc/init.d/xvfb start"
#     - sleep 3 # give xvfb some time to start

# virtualenv:
#   system_site_packages: true

install:
  - pip install --upgrade pip
  - pip install Django
  - pip install flake8
  - pip install coveralls
  - pip install -r requirements.txt

before_script:
  - flake8 edc_call_manager
  - mysql -e 'create database mb CHARACTER SET utf8;'
  - mysql -e 'create database mb_lab CHARACTER SET utf8;'

script:
  - coverage run --source=edc_call_manager manage.py test

after_success:
  - coveralls
