# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_call_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='call',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcall',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcall',
            name='subject_identifier',
            field=models.CharField(max_length=50),
        ),
    ]
