# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_call_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='call',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='call',
            name='registered_subject',
        ),
        migrations.RemoveField(
            model_name='historicalcall',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcall',
            name='registered_subject',
        ),
        migrations.RemoveField(
            model_name='historicallog',
            name='call',
        ),
        migrations.RemoveField(
            model_name='historicallog',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallogentry',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallogentry',
            name='log',
        ),
        migrations.RemoveField(
            model_name='log',
            name='call',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='log',
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='HistoricalCall',
        ),
        migrations.DeleteModel(
            name='HistoricalLog',
        ),
        migrations.DeleteModel(
            name='HistoricalLogEntry',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
