# Generated by Django 3.1.1 on 2020-10-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_call_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='delivered',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
