# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django_crypto_fields.fields.encrypted_text_field


class Migration(migrations.Migration):

    dependencies = [
        ('edc_call_manager_example', '0002_auto_20160727_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locator',
            name='contact_physical_address',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=71, null=True, verbose_name='Full physical address '),
        ),
        migrations.AlterField(
            model_name='locator',
            name='mail_address',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=71, null=True, verbose_name='Mailing address '),
        ),
        migrations.AlterField(
            model_name='locator',
            name='physical_address',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=71, null=True, verbose_name='Physical address with detailed description'),
        ),
        migrations.AlterField(
            model_name='locator',
            name='subject_identifier',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='locator',
            name='subject_work_place',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=71, null=True, verbose_name='Name and location of work place'),
        ),
    ]
